### ISSUE TITLE
Move MysqlBackend to generic PdoBackend

### ISSUE THREAD

**Issue by josegonzalez** [josegonzalez/php-queuesadilla#30]
Will need to handle oddities between Mysql connections and everything else.

**Comment by robertscherer** [comment]
Hi, first off thanks for the great package - this looks like exactly what we need.

Could you expand on this issue, maybe we can help?

**Comment by josegonzalez** [comment]
PDO uses a different DSN format for connecting to non-mysql backends. Ideally I test at least Postgres as well (which should be possible on travis).

**Comment by robertscherer** [comment]
Ok - I looked at CakePHP's Postgres driver and will use that as a guideline.

Am I right that it would be good to have `MysqlEngine` and `PostgresEngine` classes, inheriting `PdoEngine`? Especially to provide good defaults in `$baseConfig`.

**Comment by josegonzalez** [comment]
Sounds good to me.

**Comment by josegonzalez** [comment]
@robertscherer mind updating the docs for this? I'll close the issue and release then.

**Comment by robertscherer** [comment]
@josegonzalez Would you mind closing the issue and release?

Thanks,

**Comment by josegonzalez** [comment]
Done!
