### ISSUE TITLE
PdoEngine - Attempts don't work

### ISSUE THREAD

**Issue by robertscherer** [josegonzalez/php-queuesadilla#43]
The attempts feature doesn't seem to be implemented correctly in the PdoEngine. My understanding is that in `PdoEngine::release()` we also need to update the database row with the properties from the `$objects` array which is passed by the Job class.

Am I correct with this? If so, please clarify how you would want this to work and I can give it a try to finalize the feature.

**Comment by josegonzalez** [comment]
You could just do `$job->attempts() + 1` and save that. The beanstalk backend is the only one that currently supports this functionality, so however you want to set it up - either in data or as a new field - is fine by me.
