### ISSUE TITLE
PdoEngine - expires_in

### ISSUE THREAD

**Issue by cleptric** [josegonzalez/php-queuesadilla#45]
After the expires_in time is reached, the job didn't get popped anymore but remains in the table forever.
I guess it should be rejected. 
If this is to your liking, I can implement it in the PdoEngine.

**Comment by josegonzalez** [comment]
Go for it!

**Comment by robertscherer** [comment]
We should make sure there's also an event triggered when cleaning it up, in case one would want to log this for example.
