### ISSUE TITLE
Add support for passing constructor parameters for job callables

### ISSUE THREAD

**Issue by cleptric** [josegonzalez/php-queuesadilla#52]

**Comment by shadowhand** [comment]
Even better, use `psr/container` to get jobs:

```php
$job = $this->container->get($item['class']);
```

**Comment by josegonzalez** [comment]
What? Can you explain what exactly you mean by this?

**Comment by shadowhand** [comment]
Instead of requiring jobs to be callables, require that jobs are container identifiers that point to a callable. That way the job name can be anything, so long as it resolves into a callable. For instance:

```php
class HelloJob
{
    public function __invoke($job)
    {
        echo "Hello ", $job->data()['name'] ?? 'world';
    }
}

$queue->push(HelloJob::class, ['name' => 'Jose']);
```

**Comment by josegonzalez** [comment]
I still have no idea what this means, so pull requests welcome? :D
