### ISSUE TITLE
Worker max runtime

### ISSUE THREAD

**Issue by LubosRemplik** [josegonzalez/php-queuesadilla#55]
I know we should use process manager like `supervisord`, but there are scenarios we need to use simple `crontab` to schedule worker to run.

Would it be useful if I implement `workermaxruntime` param in worker constructor and use it with SequentialWorker.php?

So here 
https://github.com/josegonzalez/php-queuesadilla/blob/master/src/josegonzalez/Queuesadilla/Worker/SequentialWorker.php#L23

Would be something like

> while ($workermaxruntime > $time || $workermaxruntime == 0)

**Comment by josegonzalez** [comment]
Go for it.

**Comment by LubosRemplik** [comment]
Thanks for #56 merge
