### ISSUE TITLE
how to get  the job id when i push a job to queue

### ISSUE THREAD

**Issue by slince** [josegonzalez/php-queuesadilla#61]
You know, sometimes the  client need to track the status of job  according to id

**Comment by josegonzalez** [comment]
You can't. If you want to track the status of a job, you're going to need to assign it some other metadata and track that elsewhere. Not all backends support a form of job ticketing, and I don't think it makes sense to create an arbitrary metadata layer to do that.

I believe a workaround could be to use the `Queue.afterEnqueue` event to grab the item, which has an `id` attribute.

**Comment by slince** [comment]
Well, the second question, i found that worker and job are executed in the same process.will worker be exited if the job is wrong and terminated;

**Comment by josegonzalez** [comment]
You can crash the worker if you segfault php or throw an exception we do not catch.

**Comment by slince** [comment]
I think it's will be good that fork a child process to execute the job code;

**Comment by josegonzalez** [comment]
Feel free to implement either #12 or #13 then.

**Comment by slince** [comment]
Look forward to that.
