### ISSUE TITLE
Does this support executing shells?

### ISSUE THREAD

**Issue by davidyell** [josegonzalez/php-queuesadilla#72]
I would like to be able to schedule a job from the admin section of my application to execute a shell command.

It seems that this doesn't support executing shells from the worker. Perhaps I've misunderstood the documentation, but it seems I'd have to refactor my shell code into a library with a function and then schedule that function?

**Comment by josegonzalez** [comment]
That is correct. You could also subprocess out, or import whatever libraries are necessary for you to execute a "shell" - whatever that is - manually. All this plugin does is execute a class conforming to our job spec.
