### ISSUE TITLE
Can I re-queue failed  a job?

### ISSUE THREAD

**Issue by marufmax** [josegonzalez/php-queuesadilla#88]

**Comment by josegonzalez** [comment]
Yeah if you catch the `Worker.job.exception`, you can do whatever you want with the job.

If the job fails, it should be re-released to the queue: https://github.com/josegonzalez/php-queuesadilla/blob/master/src/josegonzalez/Queuesadilla/Worker/SequentialWorker.php#L105

Note that if you're using a newer version of CakePHP, queuing is built in (based on concepts from this project).
