### ISSUE TITLE
Beanstalkd & Pheanstalk

### ISSUE THREAD

**Issue by vonboth** [josegonzalez/php-queuesadilla#92]
Hi Jose,
does the library work with Beanstalkd && Pheanstalk?
I cannot get it to work...
I installed the library pda/pheanstalk, but when starting a queue it breaks with: 

Pheanstalk\Pheanstalk::__construct(): Argument #1 ($connection) must be of type Pheanstalk\Connection, string given

I'm using Cake 4

**Comment by josegonzalez** [comment]
This probably doesn't work with newer versions of Pheanstalk. Pull requests welcome.

I wrote the [official Queue plugin](https://book.cakephp.org/queue/1/en/index.html) based on my experience with this project, and it might better suite your needs. Supports [Pheanstalk](https://php-enqueue.github.io/transport)!

**Comment by vonboth** [comment]
Thank you for your quick reply!
